package com.friday.peanutbutter.model;

public class PostThread {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thread.id
     *
     * @mbg.generated Wed May 11 12:24:41 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thread.title
     *
     * @mbg.generated Wed May 11 12:24:41 CST 2022
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thread.gmt_create
     *
     * @mbg.generated Wed May 11 12:24:41 CST 2022
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thread.gmt_modified
     *
     * @mbg.generated Wed May 11 12:24:41 CST 2022
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thread.creator
     *
     * @mbg.generated Wed May 11 12:24:41 CST 2022
     */
    private Long creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thread.like_count
     *
     * @mbg.generated Wed May 11 12:24:41 CST 2022
     */
    private Integer likeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thread.comment_count
     *
     * @mbg.generated Wed May 11 12:24:41 CST 2022
     */
    private Integer commentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thread.view_count
     *
     * @mbg.generated Wed May 11 12:24:41 CST 2022
     */
    private Integer viewCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thread.tag
     *
     * @mbg.generated Wed May 11 12:24:41 CST 2022
     */
    private String tag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thread.description
     *
     * @mbg.generated Wed May 11 12:24:41 CST 2022
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thread.id
     *
     * @return the value of thread.id
     *
     * @mbg.generated Wed May 11 12:24:41 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thread.id
     *
     * @param id the value for thread.id
     *
     * @mbg.generated Wed May 11 12:24:41 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thread.title
     *
     * @return the value of thread.title
     *
     * @mbg.generated Wed May 11 12:24:41 CST 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thread.title
     *
     * @param title the value for thread.title
     *
     * @mbg.generated Wed May 11 12:24:41 CST 2022
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thread.gmt_create
     *
     * @return the value of thread.gmt_create
     *
     * @mbg.generated Wed May 11 12:24:41 CST 2022
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thread.gmt_create
     *
     * @param gmtCreate the value for thread.gmt_create
     *
     * @mbg.generated Wed May 11 12:24:41 CST 2022
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thread.gmt_modified
     *
     * @return the value of thread.gmt_modified
     *
     * @mbg.generated Wed May 11 12:24:41 CST 2022
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thread.gmt_modified
     *
     * @param gmtModified the value for thread.gmt_modified
     *
     * @mbg.generated Wed May 11 12:24:41 CST 2022
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thread.creator
     *
     * @return the value of thread.creator
     *
     * @mbg.generated Wed May 11 12:24:41 CST 2022
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thread.creator
     *
     * @param creator the value for thread.creator
     *
     * @mbg.generated Wed May 11 12:24:41 CST 2022
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thread.like_count
     *
     * @return the value of thread.like_count
     *
     * @mbg.generated Wed May 11 12:24:41 CST 2022
     */
    public Integer getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thread.like_count
     *
     * @param likeCount the value for thread.like_count
     *
     * @mbg.generated Wed May 11 12:24:41 CST 2022
     */
    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thread.comment_count
     *
     * @return the value of thread.comment_count
     *
     * @mbg.generated Wed May 11 12:24:41 CST 2022
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thread.comment_count
     *
     * @param commentCount the value for thread.comment_count
     *
     * @mbg.generated Wed May 11 12:24:41 CST 2022
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thread.view_count
     *
     * @return the value of thread.view_count
     *
     * @mbg.generated Wed May 11 12:24:41 CST 2022
     */
    public Integer getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thread.view_count
     *
     * @param viewCount the value for thread.view_count
     *
     * @mbg.generated Wed May 11 12:24:41 CST 2022
     */
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thread.tag
     *
     * @return the value of thread.tag
     *
     * @mbg.generated Wed May 11 12:24:41 CST 2022
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thread.tag
     *
     * @param tag the value for thread.tag
     *
     * @mbg.generated Wed May 11 12:24:41 CST 2022
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thread.description
     *
     * @return the value of thread.description
     *
     * @mbg.generated Wed May 11 12:24:41 CST 2022
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thread.description
     *
     * @param description the value for thread.description
     *
     * @mbg.generated Wed May 11 12:24:41 CST 2022
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}