package com.friday.peanutbutter.mapper;

import com.friday.peanutbutter.model.PostThread;
import com.friday.peanutbutter.model.PostThreadExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ThreadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thread
     *
     * @mbg.generated Wed May 11 12:24:41 CST 2022
     */
    long countByExample(PostThreadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thread
     *
     * @mbg.generated Wed May 11 12:24:41 CST 2022
     */
    int deleteByExample(PostThreadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thread
     *
     * @mbg.generated Wed May 11 12:24:41 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thread
     *
     * @mbg.generated Wed May 11 12:24:41 CST 2022
     */
    int insert(PostThread row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thread
     *
     * @mbg.generated Wed May 11 12:24:41 CST 2022
     */
    int insertSelective(PostThread row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thread
     *
     * @mbg.generated Wed May 11 12:24:41 CST 2022
     */
    List<PostThread> selectByExampleWithBLOBsWithRowbounds(PostThreadExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thread
     *
     * @mbg.generated Wed May 11 12:24:41 CST 2022
     */
    List<PostThread> selectByExampleWithBLOBs(PostThreadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thread
     *
     * @mbg.generated Wed May 11 12:24:41 CST 2022
     */
    List<PostThread> selectByExampleWithRowbounds(PostThreadExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thread
     *
     * @mbg.generated Wed May 11 12:24:41 CST 2022
     */
    List<PostThread> selectByExample(PostThreadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thread
     *
     * @mbg.generated Wed May 11 12:24:41 CST 2022
     */
    PostThread selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thread
     *
     * @mbg.generated Wed May 11 12:24:41 CST 2022
     */
    int updateByExampleSelective(@Param("row") PostThread row, @Param("example") PostThreadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thread
     *
     * @mbg.generated Wed May 11 12:24:41 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("row") PostThread row, @Param("example") PostThreadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thread
     *
     * @mbg.generated Wed May 11 12:24:41 CST 2022
     */
    int updateByExample(@Param("row") PostThread row, @Param("example") PostThreadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thread
     *
     * @mbg.generated Wed May 11 12:24:41 CST 2022
     */
    int updateByPrimaryKeySelective(PostThread row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thread
     *
     * @mbg.generated Wed May 11 12:24:41 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(PostThread row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thread
     *
     * @mbg.generated Wed May 11 12:24:41 CST 2022
     */
    int updateByPrimaryKey(PostThread row);
}